// export {default as add} from './Add.svg';
// export {default as card} from './Card.svg';
// export {default as cardSelected} from './Cards Selected.svg';
// export {default as cards} from './Cards';
// export {default as deck} from './Deck/svg';
// export {default as deckSelected} from './Deck Selected.svg';
// export {default as decks} from './Decks.svg';
// export {default as edit} from './Edit.svg';
// export {default as female} from './Female';
// export {default as filter} from './Filers.svg';
// export {default as galacticEmpireWatermark} from './Galactic Empire Watermark.svg';
// export {default as galacticEmpire} from './Galactic Empire.svg';
// export {default as jediOrderWatermark} from '.Jedi Order Watermark.svg';
// export {default as jediOrder} from './Jedi Order.svg';
// export {default as login} from './Login.svg';
// export {default as male} from './Male.svg';
// export {default as Move} from './Move.svg';
// export {default as rebelAllianceWatermark} from './Rebel Alliance Watermark.svg';
// export {default as rebelAlliance} from './Rebel Alliance.svg';
// export {default as remove} from './Remove.svg';
// export {default as search} from './Search.svg';
// export {default as starships} from './Starships.svg';
// export {default as user2} from './User (2).svg';
// export {default as user} from './User.svg';
// export {default as vehicles} from './Vehicles.svg';